title: KMU SW CUTIE'S BLOG
description: 나 국민대 귀염둥이 한초희

url: https://choheehan.gitpage.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: choheehan
  email: cherror@kookmin.ac.kr

google_analytics: "UA-58263416-1"

comment:
  provider: "disqus"
  disqus:
    shortname: "choheehan"
